lims/urls.py
from django.urls import path

from . import views

app_name = 'lims'

urlpatterns = [
    path('', views.index, name="index"),
    path('samples/', views.SampleListView.as_view(), name="sample_list"),
    path('samples/json/', views.sample_list_json_view, name="sample_list_json"),
    path('samples/search/', views.search_view, name="sample_search"),
    path('samples/detail/<str:pk>/', views.SampleDetailView.as_view(), name="sample_detail"),
    path('samples/detail/<str:pk>/result/new', views.SampleResultSampleFormView.as_view(), name="new_result_sample"),
    path('samples/detail/<str:pk>/edit/', views.SampleUpdateView.as_view(), name="edit_sample"),
    path('samples/event/<str:event_id>/', views.event_samples, name="event_samples"),
    path('samples/add/', views.add_samples, name="new_samples"),
    path('samples/add/<str:event_id>/<str:sample_type>', views.verify_subjects, name="verify_new_samples"),
    path('samples/event/<str:event_id>/sample-label-options/', views.sample_label_options, name="sample_labels_options"),
    path('samples/sample-storage-label-options/', views.sample_storage_label_options, name="sample_storage_labels_options"),
    path('projects/', views.ProjectListView.as_view(), name="project_list"),
    path('projects/detail/<str:pk>/', views.ProjectDetailView.as_view(), name="project_detail"),
    path('projects/detail/<str:pk>/edit/', views.ProjectUpdateView.as_view(), name="edit_project"),
    path('projects/new/', views.ProjectFormView.as_view(), name="new_project"),
    path('project/detail/<str:pk>/remove/', views.ProjectDeleteView.as_view(), name="delete_project"),
    path('locations/', views.LocationListView.as_view(), name="location_list"),
    path('locations/new/', views.LocationFormView.as_view(), name="new_location"),
    path('locations/detail/<str:pk>/', views.LocationDetailView.as_view(), name="location_detail"),
    path('locations/detail/<str:pk>/edit/', views.LocationUpdateView.as_view(), name="edit_location"),
    path('locations/detail/<str:pk>/remove/', views.LocationDeleteView.as_view(), name="delete_location"),
    path('researchers/', views.ResearcherListView.as_view(), name="researcher_list"),
    path('researchers/new/', views.ResearcherFormView.as_view(), name="new_researcher"),
    path('researchers/detail/<str:pk>/', views.ResearcherDetailView.as_view(), name="researcher_detail"),
    path('researchers/detail/<str:pk>/edit/', views.ResearcherUpdateView.as_view(), name="edit_researcher"),
    path('researchers/detail/<str:pk>/remove/', views.ResearcherDeleteView.as_view(), name="delete_researcher"),
    path('subject/', views.SubjectListView.as_view(), name="subject_list"),
    path('subject/json/', views.subject_list_json_view, name="subject_list_json"),
    path('subject/detail_list', views.SubjectDetailListView.as_view(), name="subject_list_detail"),
    path('subject/new/', views.SubjectFormView.as_view(), name="new_subject"),
    path('subject/detail/<str:pk>/', views.SubjectDetailView.as_view(), name="subject_detail"),
    path('subject/detail/<str:pk>/edit/', views.SubjectUpdateView.as_view(), name="edit_subject"),
    path('subject/detail/<str:pk>/remove/', views.SubjectDeleteView.as_view(), name="delete_subject"),
    path('event/', views.EventListView.as_view(), name="event_list"),
    path('event/new/', views.EventFormView.as_view(), name="new_event"),
    path('event/detail/<str:pk>/', views.EventDetailView.as_view(), name="event_detail"),
    path('event/detail/<str:pk>/edit/', views.EventUpdateView.as_view(), name="edit_event"),
    path('event/detail/<str:pk>/remove/', views.EventDeleteView.as_view(), name="delete_event"),
    path('event/notices/', views.sample_notices, name="sample_notice"),
    path('event/detail/<str:event_id>/notice-text/', views.sample_notices, name="sample_notice_text"),
    path('event/<str:event_id>/notices/', views.sample_notices_pdf, name="sample_notice_pdf"),
    path('event/choose-event/', views.select_event_for_sample, name="select_sample_event"),
    path('event/list/choose-event/', views.select_event_for_sample_list, name="select_sample_event_list"),
    path('event/<str:event_id>/subject-list/', views.subject_list, name="subject_list"),
    path('sample-box/', views.SampleBoxListView.as_view(), name="sample_box_list"),
    path('sample-box/new/', views.SampleBoxFormView.as_view(), name="new_sample_box"),
    path('sample-box/detail/<str:pk>/', views.SampleBoxDetailView.as_view(), name="sample_box_detail"),
    path('sample-box/detail/<str:pk>/edit/', views.SampleBoxUpdateView.as_view(), name="edit_sample_box"),
    path('sample-box/detail/<str:pk>/remove/', views.SampleBoxDeleteView.as_view(), name="delete_sample_box"),
    path('sample-box/detail/<str:pk>/copy-samples/', views.SampleBoxCopySamples.as_view(), name="sample_box_copy_samples"),
    path('sample-box/detail/<str:pk>/upload-samples/', views.SampleBoxPositionUploadView.as_view(), name="sample_box_upload_samples"),
    path('sample-box/detail/<str:pk_box>/position/<str:pk>/', views.SampleBoxPosDetailView.as_view(), name="sample_box_position_detail"),
    path('sample-box/detail/<str:pk_box>/position/<str:pk>/edit-sample/', views.SampleBoxPositionUpdateView.as_view(), name="edit_sample_box_position"),
    path('sample-box/detail/<str:pk_box>/position/<str:pk>/add-samples/', views.SampleBoxPositionContinuousUpdateView.as_view(), name="edit_sample_box_position_continuous"),
    path('pool-box/', views.PoolBoxListView.as_view(), name="pool_box_list"),
    path('pool-box/new/', views.PoolBoxFormView.as_view(), name="new_pool_box"),
    path('pool-box/detail/<str:pk>/', views.PoolBoxDetailView.as_view(), name="pool_box_detail"),
    path('pool-box/detail/<str:pk>/edit/', views.PoolBoxUpdateView.as_view(), name="edit_pool_box"),
    path('pool-box/detail/<str:pk>/remove/', views.PoolBoxDeleteView.as_view(), name="delete_pool_box"),
    path('pool-box/detail/<str:pk_box>/position/<str:pk>/', views.PoolBoxPosDetailView.as_view(), name="pool_box_position_detail"),
    path('pool-box/detail/<str:pk_box>/position/<str:pk>/edit-pool/', views.PoolBoxPositionUpdateView.as_view(), name="edit_pool_box_position"),
    path('pool-box/detail/<str:pk_box>/position/<str:pk>/add-pools/', views.PoolBoxPositionContinuousUpdateView.as_view(), name="edit_pool_box_position_continuous"),
    path('pool/', views.PoolListView.as_view(), name="pool_list"),
    path('pool/new/', views.PoolFormView.as_view(), name="new_pool"),
    path('pool/detail/<str:pk>/add-samples', views.PoolAddSamples.as_view(), name="add_pool_samples"),
    path('pool/detail/<str:pk>/add-pools', views.PoolAddPools.as_view(), name="add_pool_pools"),
    path('pool/detail/<str:pk>/result/new', views.PoolResultSampleFormView.as_view(), name="new_result_pool"),
    path('pool/detail/<str:pk>/', views.PoolDetailView.as_view(), name="pool_detail"),
    path('pool/detail/<str:pk>/edit/', views.PoolUpdateView.as_view(), name="edit_pool"),
    path('pool/detail/<str:pk>/remove/', views.PoolDeleteView.as_view(), name="delete_pool"),
    path('pool/detail/<str:pk>/report/', views.PoolReportDetailView.as_view(), name="pool_report"),
    path('fix-ids/', views.fix_ids, name="fix_ids"),
    path('labels/', views.LabelListView.as_view(), name="label_list"),
    path('labels/new/', views.LabelFormView.as_view(), name="new_label"),
    path('labels/detail/<str:pk>/', views.LabelDetailView.as_view(), name="label_detail"),
    path('labels/detail/<str:pk>/edit/', views.LabelUpdateView.as_view(), name="edit_label"),
    path('labels/detail/<str:pk>/remove/', views.LabelDeleteView.as_view(), name="delete_label"),
    path('test/', views.TestListView.as_view(), name="test_list"),
    path('test/new/', views.TestFormView.as_view(), name="new_test"),
    path('test/detail/<str:pk>/', views.TestDetailView.as_view(), name="test_detail"),
    path('test/detail/<str:pk>/edit/', views.TestUpdateView.as_view(), name="edit_test"),
    path('test/detail/<str:pk>/remove/', views.TestDeleteView.as_view(), name="delete_test"),
    path('sequencing/', views.SequenceListView.as_view(), name="sequence_list"),
    path('sequencing/new/', views.SequenceFormView.as_view(), name="new_sequence"),
    path('sequencing/detail/<str:pk>/', views.SequenceDetailView.as_view(), name="sequence_detail"),
    path('sequencing/detail/<str:pk>/add-samples', views.SequenceAddSamples.as_view(), name="add_sequence_samples"),
    path('sequencing/detail/<str:pk>/add-pools', views.SequenceAddPools.as_view(), name="add_sequence_pools"),
    path('sequencing/detail/<str:pk>/edit/', views.SequenceUpdateView.as_view(), name="edit_sequence"),
    path('sequencing/detail/<str:pk>/remove/', views.SequenceDeleteView.as_view(), name="delete_sequence"),
    path('sequencing/sample-list/', views.sequenced_samples, name="sequenced_samples"),
    path('sequencing/data/', views.sequencing_endpoint, name='sequencing_endpoint'),
    path('sample-result/', views.SampleResultListView.as_view(), name="sample_result_list"),
    path('sample-result/new/', views.SampleResultFormView.as_view(), name="new_sample_result"),
    path('sample-result/upload/', views.upload_sample_result_file, name="upload_sample_result"),
    path('sample-result/add-multiple/', views.sampleresult_multiple_view, name="new_multi_sample_result"),
    path('sample-result/add-multiple/<str:test_id>/<str:rep>/add-samples/', views.sampleresult_multiple_add_samples, name="sampleresult_multiple_add_samples"),
    path('sample-result/detail/<str:pk>/', views.SampleResultDetailView.as_view(), name="sample_result_detail"),
    path('sample-result/detail/<str:pk>/edit/', views.SampleResultUpdateView.as_view(), name="edit_sample_result"),
    path('sample-result/detail/<str:pk>/remove/', views.SampleResultDeleteView.as_view(), name="delete_sample_result"),
    path('pool-result/', views.PoolResultListView.as_view(), name="pool_result_list"),

out_on_a_LIMS/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from lims.views import index

urlpatterns = [
    path('', index, name="index"),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name="password_change"),
    path('users/', include('users.urls')),
    path('lims/', include('lims.urls')),
]

lims/templates/lims/event_detail.html
{% extends "lims/base.html" %}
{% block content %}
<div class="card">
    <h1 class="card-header">Event: {{ event.name }}</h1>
    <div class="card-body">
      <p class="card-text"><strong>Description:</strong> {{ event.description }}</p>
    </div>
    <h4 class="card-header">Locations:</h4>
    <div class="card-body">
      <ul class="list-group list-group-flush">
          {% for location in event.location.all %}
          <li class="list-group-item">
          <a href="{% url 'lims:location_detail' location.id %}">{{ location.name }}</a></li>
          {% endfor %}
      </ul>
    </div>
    <h4 class="card-header">Collected By:</h4>
    <ul class="list-group" list-group-flush">
      {% for researcher in event.researcher.all %}
      <li class="list-group-item"><a href="{% url 'lims:researcher_detail' researcher.id %}" >{{ researcher.name }}</a></li>
      {% endfor %}
      <li class="list-group-item"><Strong>Collection Date: </Strong>{{ event.date }}</li>
      <li class="list-group-item"><Strong>Event Week: </Strong>{{ event.week }}</li>
      <li class="list-group-item"><strong>Notes: </strong>{{ event.notes }}</li>
      <li class="list-group-item"><strong>Created: </strong>{{ event.created_on }}</li>
    </ul>
  </div>
  <div class="d-grid gap-0 d-md-block mt-2">
        <a class="btn btn-primary btn mb-2" href="{% url 'lims:edit_event' event.id %}" role="button">Edit <span data-feather="edit"></span></a>
        {% if event.is_complete == False %}
          <a class="btn btn-primary btn mb-2" href="{% url 'lims:subject_list' event.id %}" role="button">Print Participant List <span data-feather="printer"></span></a>
          <a class="btn btn-primary btn mb-2" href="{% url 'lims:sample_notice_text' event.id %}" role="button">Print Notices <span data-feather="printer"></span></a>
          {% endif %}
        <a class="btn btn-primary btn mb-2" href="mailto:{{ event.get_subject_email_list }}" target="_blank" rel="noopener noreferrer" role="button">Email Participants <span data-feather="mail"></span></a>
        <a class="btn btn-outline-primary btn mb-2" href="{% url 'lims:new_event' %}" role="button">Add New Event <span data-feather="plus"></span></a>
        <a class="btn btn-outline-primary btn mb-2" href="{% url 'lims:event_list' %}" role="button">Events <span data-feather="corner-up-left"></span></a>
        <a class="btn btn-outline-primary btn mb-2" href="{% url 'lims:index' %}" role="button">Home <span data-feather="corner-up-left"></span></a>
        <a class="btn btn-outline-danger btn mb-2" href="{% url 'lims:delete_event' event.id %}" role="button">Delete <span data-feather="trash"></span></a>
    </div>

{% endblock content %}

lims/templates/lims/location_detail.html
{% extends "lims/base.html" %}
{% block content %}
<div class="card">
    <h1 class="card-header">Location: {{ location.name }}</h1>
    <div class="card-body">
      <p class="card-text"><strong>Type:</strong> {{ location.location_type }}</p>      
      <p class="card-text"><strong>Description:</strong> {{ location.description }}</p>      
    </div>
    <ul class="list-group list-group-flush">
      {% if location.project %}
      <li class="list-group-item"><strong>Project:</strong> <a href="{% url 'lims:project_detail' location.project.id %}">{{ location.project.name }}</a></li>
      {% else %}
      <li class="list-group-item"><strong>Project:</strong> None</li>
      {% endif %}
      <li class="list-group-item"><strong>Grade:</strong> {{ location.grade }}</li>
      <li class="list-group-item"><strong>Address:</strong> {{ location.address }}</li>
      <li class="list-group-item"><strong>Classroom:</strong> {{ location.classroom }}</li>
      <li class="list-group-item"><strong>Contact Name:</strong> {{ location.contact_name }}</li>
      <li class="list-group-item"><strong>Contact Email:</strong> {{ location.contact_email }}</li>
      <li class="list-group-item"><Strong>Contact Phone:</Strong> {{ location.contact_phone }}</li>
      <li class="list-group-item"><Strong>Created:</Strong> {{ location.created_on }}</li>
    </ul>
  </div>
  <div class="d-grid gap-0 d-md-block mt-2">
      <a class="btn btn-primary btn mb-2" href="{% url 'lims:edit_location' location.id %}" role="button">Edit <span data-feather="edit"></span></a>
      <a class="btn btn-outline-primary btn mb-2" href="{% url 'lims:new_location' %}" role="button">Add New Location <span data-feather="plus"></span></a>
      <a class="btn btn-outline-primary btn mb-2" href="{% url 'lims:location_list' %}" role="button">Locations <span data-feather="corner-up-left"></span></a>
      <a class="btn btn-outline-primary btn mb-2" href="{% url 'lims:index' %}" role="button">Home <span data-feather="corner-up-left"></span></a>
      <a class="btn btn-outline-danger btn mb-2" href="{% url 'lims:delete_location' location.id %}" role="button">Delete <span data-feather="trash"></span></a>
  </div>

{% endblock content %}

lims/templates/lims/project_list.html
{% extends "lims/base.html" %}
{% block head %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.11.3/af-2.3.7/b-2.0.1/b-colvis-2.0.1/b-html5-2.0.1/b-print-2.0.1/cr-1.5.4/date-1.1.1/fc-4.0.0/fh-3.2.0/kt-2.6.4/r-2.2.9/rr-1.2.8/sb-1.2.2/sl-1.3.3/datatables.min.css"/>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/rowreorder/1.2.8/css/rowReorder.dataTables.min.css"/>
{% endblock head %}

{% block content %}
<h1 class="border-bottom">Projects</h1>
    <div class="d-grid gap-2 d-md-block mt-2 mb-2">
        <a class="btn btn-primary btn" href="{% url 'lims:new_project' %}" role="button">New Project <span data-feather="plus"></span></a>
    </div>
    

    <table id="project_table" class="display table table-hover"  align="center"  style="width:100%"> 
        <thead>
            
            <tr>
                <th>Project Name</th>
                <th>Lead Investigator</th>
                <th>Start Date</th>
                <th>End Date</th>
            </tr>
        </thead>
        <tbody>
            {% for project in project_list %}
                <tr>
                    <td><a class="table-link" href="{% url 'lims:project_detail' project.id %}">
                        {{ project.name }}
                    </a></td>
                    <td>{{ project.investigator }}</td>
                    <td>{{ project.start_date }}</td>
                    <td>{{ project.end_date }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock content %}

{% block js %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.11.3/af-2.3.7/b-2.0.1/b-colvis-2.0.1/b-html5-2.0.1/b-print-2.0.1/cr-1.5.4/date-1.1.1/fc-4.0.0/fh-3.2.0/kt-2.6.4/r-2.2.9/rr-1.2.8/sb-1.2.2/sl-1.3.3/datatables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/rowgroup/1.1.3/js/dataTables.rowGroup.min.js"></script>
<script>
    $(document).ready( function () {
    $('#project_table').DataTable({
    rowReorder: false,
    fixedHeader: true,
    stateSave: true,
    order: [],
    aLengthMenu: [
            [25, 50, 100, 200, -1],
            [25, 50, 100, 200, "All"]
            ],
    iDisplayLength: 25,
    dom: 'B<"clear">lfrtip',
    columns: [
        {data: "Project Name"},
        {data: "Lead Investigator"},
        {
            data: "Start Date",
            type: "date"
        },
        {
            data: "End Date",
            type: "date"
        }
    ],
    buttons: {
        name: 'primary',
        buttons: [ 
        {
          extend: 'copy',
          title: 'Project List'
        },
        {
          extend: 'pdf',
          title: 'Project List'
        },
        {
          extend: 'csv',
          title: 'Project List'
        },
        {
          extend: 'excel',
          title: 'Project List'
        }]

        }}
    );
} );
</script>
{% endblock js %}

lims/templates/lims/sample_list.html
{% extends "lims/base.html" %}
{% load static %}
{% block head %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.11.3/af-2.3.7/b-2.0.1/b-colvis-2.0.1/b-html5-2.0.1/b-print-2.0.1/cr-1.5.4/date-1.1.1/fc-4.0.0/fh-3.2.0/kt-2.6.4/r-2.2.9/rr-1.2.8/sb-1.2.2/sl-1.3.3/datatables.min.css"/>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/rowreorder/1.2.8/css/rowReorder.dataTables.min.css"/>
<link rel="stylesheet" type="text/css" source="{% static 'lims/data-tables/css/editor.dataTables.min.css' %}"/>
<link rel="stylesheet" type="text/css" source="{% static 'lims/data-tables/css/editor.bootstrap5.min.css' %}"/>

{% endblock head %}

{% block content %}
{% csrf_token %}
<h1 class="border-bottom">Samples</h1>
<div class="d-grid gap-2 d-md-block mt-2 mb-2">
        <a class="btn btn-primary btn" href="{% url 'lims:new_samples' %}" role="button">Add Samples <span data-feather="plus"></span></a>
        <a class="btn btn-primary btn" href="{% url 'lims:select_sample_event' %}" role="button">Print Sample Labels <span data-feather="printer"></span></a>
        <a class="btn btn-primary btn" href="{% url 'lims:sample_storage_labels_options' %}" role="button">Print Storage Labels <span data-feather="printer"></span></a>
        <a class="btn btn-primary btn" href="{% url 'lims:label_list' %}" role="button">Label Formats <span data-feather="columns"></span></a>
    </div>
    <table id="sample_table" class="display table table-hover"> 
        <thead>
            <tr>
                <th>Sample ID</th>
                <th>Subject ID</th>
                <th>Collection Event</th>
                <th>Location</th>
                <th>Grade</th>
                <th>Collection Status</th>
                <th>Sample Type</th>
            </tr>
        </thead>
        
    </table>

{% endblock content %}

{% block js %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.11.3/af-2.3.7/b-2.0.1/b-colvis-2.0.1/b-html5-2.0.1/b-print-2.0.1/cr-1.5.4/date-1.1.1/fc-4.0.0/fh-3.2.0/kt-2.6.4/r-2.2.9/rr-1.2.8/sb-1.2.2/sl-1.3.3/datatables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/rowgroup/1.1.3/js/dataTables.rowGroup.min.js"></script>
<script type="text/javascript" src="{% static 'lims/data-tables/js/dataTables.editor.min.js' %}"></script>
<script type="text/javascript" src="{% static 'lims/data-tables/js/editor.bootstrap5.min.js' %}"></script>
<script type="text/javascript" src="{% static 'lims/data-tables/js/editor.dataTables.min.js' %}"></script>

<script>

 $.ajaxSetup({
    data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
 });
 let editor; // use a global for the submit and return data rendering in the examples
 $(document).ready(function() {
     editor = new $.fn.dataTable.Editor( {
        //  ajax: {
        //     url: "{% url 'lims:sample_table_update' %}",
        //     type: "POST",
        //     dataType: "json",
        //     success: () => {
        //         $('#sample_table').DataTable().ajax.reload()
        //         }
        //  },
         ajax: "{% url 'lims:sample_table_update' %}",
         table: "#sample_table",
         idSrc:  'id',
         fields: [ 
             
             {
                 label: "Sample ID",
                 name: "name",
                 type: "readonly",
             },
            {
                label: "Subject ID",
                name: "subject__subject_ui",
                type: "readonly",
            },
            {
                label: "Collection Event",
                name: "collection_event__name",
                type: "readonly",
            },
            {
                label: "Location",
                name: "location__name",
                type: "readonly",
            },
            {
                label: "Grade",
                name: "location__grade",
                type: "readonly",
            },
            {
                label: "Collection Status",
                name: "collection_status",
                type:  "select",
                options: [
                    { label: "Collected", value: "Collected" },
                    { label: "Pending", value: "Pending" },
                    { label: "Refused", value: "Refused" },
                    { label: "Absent", value: "Absent" },
                    { label: "Withdrew",  value: "Withdrew" },
                ]
            },
            {
                label: "Sample Type",
                name: "sample_type",
                type: "readonly"
            },
         ]
     } );
    
    // Activate an inline edit on click of a table cell
    $('#sample_table').on( 'click', 'tbody td:nth-child(6)', function (e) {
        editor.inline( this, {submit: 'all', onBlur: 'submit'} );
    } );
    
    // $('#sample_table').on( 'click', 'tbody td:not(:first-child)', function (e) {
    //     editor.bubble( this );
    // } );

    var collection_status = {
        Collected: "success",
        Pending: "secondary",
        Absent: "warning",
        Refused: "warning",
        Withdrew: "danger",
    }
    
    $('#sample_table').DataTable({
    rowReorder: false,
    fixedHeader: true,
    stateSave: true,
    ajax: {
        url:"{% url 'lims:sample_list_json' %}",
        csrfmiddlewaretoken: '{{ csrf_token }}' 
        },
    order: [],
    aLengthMenu: [
            [25, 50, 100, 200, -1],
            [25, 50, 100, 200, "All"]
            ],
    iDisplayLength: 25,
    dom: 'B<"clear">lfrtip',
    columns: [
            { 
              data: "name",
              render: function ( data, type, row ) {
                let str = '<a class="table-link" href="{% url 'lims:sample_detail' 1 %}">' + data + '</a>'
                let newstr = str.replace("1", row.id)
                return newstr
            }},
            { data: "subject__subject_ui",
              render: function ( data, type, row ) {
                let str = '<a class="table-link" href="{% url 'lims:subject_detail' 1 %}">' + data + '</a>'
                let newstr = str.replace("1", row.subject__id)
                return newstr
            }},
            { data: "collection_event__name" ,
              render: function ( data, type, row ) {
                let str = '<a class="table-link" href="{% url 'lims:event_detail' 1 %}">' + data + '</a>'
                let newstr = str.replace("1", row.collection_event__id)
                return newstr
            }},
            { data: "location__name",
              render: function ( data, type, row ) {
                let str = '<a class="table-link" href="{% url 'lims:location_detail' 1 %}">' + data + '</a>'
                let newstr = str.replace("1", row.location__id)
                return newstr
            }},
            {
                data: "location__grade"
            },
            { 
                "data": "collection_status",
                render: function ( status ) {
                            return status ?
                                `<span class="badge bg-${collection_status[status]}">${status}</span>` : null     
                        }
            },
            { data: "sample_type" },
   
        ],
    select: {
        style: 'multi+shift',
    },
    buttons: {
        name: 'primary',
        buttons: [ 
        {
          extend: 'copy',
          title: 'Sample List'
        },
        {
          extend: 'pdf',
          title: 'Sample List'
        },
        {
          extend: 'csv',
          title: 'Sample List'
        },
        {
          extend: 'excel',
          title: 'Sample List'
        },
        { extend: "edit",   editor: editor }]
        }}
    );
} );
</script>
{% endblock js %}